# Exported from Render on 2026-08-14T05:02:49Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: VCH
      runtime: python
      repo: https://github.com/Bra-ndy/VCH
      plan: free
      envVars:
      - key: PYTHON_VERSION
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
      - key: MPESA_SHORTCOD
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_ENVIRONMENT
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: APP_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        sync: false
      region: ohio
      buildCommand: pip install -r requirements.txt
      startCommand: python app_light.py
      autoDeployTrigger: commit
    databases:
    - name: vch-production-db
      databaseName: vch_production
      user: vch_prod_user
      plan: free
      region: ohio
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
